name: agro_dost
description: AI Agro Mandi Dost
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.4
  image_picker: ^1.0.7
  image: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/models/plant_model.tflite
